name: Run Guild Wars 2 API tests

on:
  push:
    branches:
      - main

  pull_request:

env:
  GW2_API_KEY: ${{ secrets.GW2_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.0'
          - '2.7.8'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the tests
      run: bundle exec rake
